// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: exec/msg/console.proto

package com.bearsnake.khalehla.kdte.console.messages;

public interface PollInputMessageResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:msg.PollInputMessageResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool hasInput = 1;</code>
   * @return The hasInput.
   */
  boolean getHasInput();

  /**
   * <code>.msg.SolicitedInputMessage solicitedMessage = 2;</code>
   * @return Whether the solicitedMessage field is set.
   */
  boolean hasSolicitedMessage();
  /**
   * <code>.msg.SolicitedInputMessage solicitedMessage = 2;</code>
   * @return The solicitedMessage.
   */
  com.bearsnake.khalehla.kdte.console.messages.SolicitedInputMessage getSolicitedMessage();
  /**
   * <code>.msg.SolicitedInputMessage solicitedMessage = 2;</code>
   */
  com.bearsnake.khalehla.kdte.console.messages.SolicitedInputMessageOrBuilder getSolicitedMessageOrBuilder();

  /**
   * <code>.msg.UnsolicitedInputMessage unsolicitedMessage = 3;</code>
   * @return Whether the unsolicitedMessage field is set.
   */
  boolean hasUnsolicitedMessage();
  /**
   * <code>.msg.UnsolicitedInputMessage unsolicitedMessage = 3;</code>
   * @return The unsolicitedMessage.
   */
  com.bearsnake.khalehla.kdte.console.messages.UnsolicitedInputMessage getUnsolicitedMessage();
  /**
   * <code>.msg.UnsolicitedInputMessage unsolicitedMessage = 3;</code>
   */
  com.bearsnake.khalehla.kdte.console.messages.UnsolicitedInputMessageOrBuilder getUnsolicitedMessageOrBuilder();

  com.bearsnake.khalehla.kdte.console.messages.PollInputMessageResponse.InputSpecifierCase getInputSpecifierCase();
}
