// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: exec/msg/console.proto

package com.bearsnake.khalehla.kdte.console.messages;

/**
 * Protobuf type {@code msg.PollInputMessageResponse}
 */
public final class PollInputMessageResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:msg.PollInputMessageResponse)
    PollInputMessageResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PollInputMessageResponse.newBuilder() to construct.
  private PollInputMessageResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PollInputMessageResponse() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new PollInputMessageResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.bearsnake.khalehla.kdte.console.messages.ConsoleService.internal_static_msg_PollInputMessageResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.bearsnake.khalehla.kdte.console.messages.ConsoleService.internal_static_msg_PollInputMessageResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.bearsnake.khalehla.kdte.console.messages.PollInputMessageResponse.class, com.bearsnake.khalehla.kdte.console.messages.PollInputMessageResponse.Builder.class);
  }

  private int inputSpecifierCase_ = 0;
  @SuppressWarnings("serial")
  private java.lang.Object inputSpecifier_;
  public enum InputSpecifierCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    SOLICITEDMESSAGE(2),
    UNSOLICITEDMESSAGE(3),
    INPUTSPECIFIER_NOT_SET(0);
    private final int value;
    private InputSpecifierCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static InputSpecifierCase valueOf(int value) {
      return forNumber(value);
    }

    public static InputSpecifierCase forNumber(int value) {
      switch (value) {
        case 2: return SOLICITEDMESSAGE;
        case 3: return UNSOLICITEDMESSAGE;
        case 0: return INPUTSPECIFIER_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public InputSpecifierCase
  getInputSpecifierCase() {
    return InputSpecifierCase.forNumber(
        inputSpecifierCase_);
  }

  public static final int HASINPUT_FIELD_NUMBER = 1;
  private boolean hasInput_ = false;
  /**
   * <code>bool hasInput = 1;</code>
   * @return The hasInput.
   */
  @java.lang.Override
  public boolean getHasInput() {
    return hasInput_;
  }

  public static final int SOLICITEDMESSAGE_FIELD_NUMBER = 2;
  /**
   * <code>.msg.SolicitedInputMessage solicitedMessage = 2;</code>
   * @return Whether the solicitedMessage field is set.
   */
  @java.lang.Override
  public boolean hasSolicitedMessage() {
    return inputSpecifierCase_ == 2;
  }
  /**
   * <code>.msg.SolicitedInputMessage solicitedMessage = 2;</code>
   * @return The solicitedMessage.
   */
  @java.lang.Override
  public com.bearsnake.khalehla.kdte.console.messages.SolicitedInputMessage getSolicitedMessage() {
    if (inputSpecifierCase_ == 2) {
       return (com.bearsnake.khalehla.kdte.console.messages.SolicitedInputMessage) inputSpecifier_;
    }
    return com.bearsnake.khalehla.kdte.console.messages.SolicitedInputMessage.getDefaultInstance();
  }
  /**
   * <code>.msg.SolicitedInputMessage solicitedMessage = 2;</code>
   */
  @java.lang.Override
  public com.bearsnake.khalehla.kdte.console.messages.SolicitedInputMessageOrBuilder getSolicitedMessageOrBuilder() {
    if (inputSpecifierCase_ == 2) {
       return (com.bearsnake.khalehla.kdte.console.messages.SolicitedInputMessage) inputSpecifier_;
    }
    return com.bearsnake.khalehla.kdte.console.messages.SolicitedInputMessage.getDefaultInstance();
  }

  public static final int UNSOLICITEDMESSAGE_FIELD_NUMBER = 3;
  /**
   * <code>.msg.UnsolicitedInputMessage unsolicitedMessage = 3;</code>
   * @return Whether the unsolicitedMessage field is set.
   */
  @java.lang.Override
  public boolean hasUnsolicitedMessage() {
    return inputSpecifierCase_ == 3;
  }
  /**
   * <code>.msg.UnsolicitedInputMessage unsolicitedMessage = 3;</code>
   * @return The unsolicitedMessage.
   */
  @java.lang.Override
  public com.bearsnake.khalehla.kdte.console.messages.UnsolicitedInputMessage getUnsolicitedMessage() {
    if (inputSpecifierCase_ == 3) {
       return (com.bearsnake.khalehla.kdte.console.messages.UnsolicitedInputMessage) inputSpecifier_;
    }
    return com.bearsnake.khalehla.kdte.console.messages.UnsolicitedInputMessage.getDefaultInstance();
  }
  /**
   * <code>.msg.UnsolicitedInputMessage unsolicitedMessage = 3;</code>
   */
  @java.lang.Override
  public com.bearsnake.khalehla.kdte.console.messages.UnsolicitedInputMessageOrBuilder getUnsolicitedMessageOrBuilder() {
    if (inputSpecifierCase_ == 3) {
       return (com.bearsnake.khalehla.kdte.console.messages.UnsolicitedInputMessage) inputSpecifier_;
    }
    return com.bearsnake.khalehla.kdte.console.messages.UnsolicitedInputMessage.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (hasInput_ != false) {
      output.writeBool(1, hasInput_);
    }
    if (inputSpecifierCase_ == 2) {
      output.writeMessage(2, (com.bearsnake.khalehla.kdte.console.messages.SolicitedInputMessage) inputSpecifier_);
    }
    if (inputSpecifierCase_ == 3) {
      output.writeMessage(3, (com.bearsnake.khalehla.kdte.console.messages.UnsolicitedInputMessage) inputSpecifier_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (hasInput_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, hasInput_);
    }
    if (inputSpecifierCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (com.bearsnake.khalehla.kdte.console.messages.SolicitedInputMessage) inputSpecifier_);
    }
    if (inputSpecifierCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (com.bearsnake.khalehla.kdte.console.messages.UnsolicitedInputMessage) inputSpecifier_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.bearsnake.khalehla.kdte.console.messages.PollInputMessageResponse)) {
      return super.equals(obj);
    }
    com.bearsnake.khalehla.kdte.console.messages.PollInputMessageResponse other = (com.bearsnake.khalehla.kdte.console.messages.PollInputMessageResponse) obj;

    if (getHasInput()
        != other.getHasInput()) return false;
    if (!getInputSpecifierCase().equals(other.getInputSpecifierCase())) return false;
    switch (inputSpecifierCase_) {
      case 2:
        if (!getSolicitedMessage()
            .equals(other.getSolicitedMessage())) return false;
        break;
      case 3:
        if (!getUnsolicitedMessage()
            .equals(other.getUnsolicitedMessage())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + HASINPUT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getHasInput());
    switch (inputSpecifierCase_) {
      case 2:
        hash = (37 * hash) + SOLICITEDMESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getSolicitedMessage().hashCode();
        break;
      case 3:
        hash = (37 * hash) + UNSOLICITEDMESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getUnsolicitedMessage().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.bearsnake.khalehla.kdte.console.messages.PollInputMessageResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bearsnake.khalehla.kdte.console.messages.PollInputMessageResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bearsnake.khalehla.kdte.console.messages.PollInputMessageResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bearsnake.khalehla.kdte.console.messages.PollInputMessageResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bearsnake.khalehla.kdte.console.messages.PollInputMessageResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bearsnake.khalehla.kdte.console.messages.PollInputMessageResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bearsnake.khalehla.kdte.console.messages.PollInputMessageResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.bearsnake.khalehla.kdte.console.messages.PollInputMessageResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.bearsnake.khalehla.kdte.console.messages.PollInputMessageResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.bearsnake.khalehla.kdte.console.messages.PollInputMessageResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.bearsnake.khalehla.kdte.console.messages.PollInputMessageResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.bearsnake.khalehla.kdte.console.messages.PollInputMessageResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.bearsnake.khalehla.kdte.console.messages.PollInputMessageResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code msg.PollInputMessageResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:msg.PollInputMessageResponse)
      com.bearsnake.khalehla.kdte.console.messages.PollInputMessageResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bearsnake.khalehla.kdte.console.messages.ConsoleService.internal_static_msg_PollInputMessageResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bearsnake.khalehla.kdte.console.messages.ConsoleService.internal_static_msg_PollInputMessageResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bearsnake.khalehla.kdte.console.messages.PollInputMessageResponse.class, com.bearsnake.khalehla.kdte.console.messages.PollInputMessageResponse.Builder.class);
    }

    // Construct using com.bearsnake.khalehla.kdte.console.messages.PollInputMessageResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      hasInput_ = false;
      if (solicitedMessageBuilder_ != null) {
        solicitedMessageBuilder_.clear();
      }
      if (unsolicitedMessageBuilder_ != null) {
        unsolicitedMessageBuilder_.clear();
      }
      inputSpecifierCase_ = 0;
      inputSpecifier_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.bearsnake.khalehla.kdte.console.messages.ConsoleService.internal_static_msg_PollInputMessageResponse_descriptor;
    }

    @java.lang.Override
    public com.bearsnake.khalehla.kdte.console.messages.PollInputMessageResponse getDefaultInstanceForType() {
      return com.bearsnake.khalehla.kdte.console.messages.PollInputMessageResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.bearsnake.khalehla.kdte.console.messages.PollInputMessageResponse build() {
      com.bearsnake.khalehla.kdte.console.messages.PollInputMessageResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.bearsnake.khalehla.kdte.console.messages.PollInputMessageResponse buildPartial() {
      com.bearsnake.khalehla.kdte.console.messages.PollInputMessageResponse result = new com.bearsnake.khalehla.kdte.console.messages.PollInputMessageResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartial0(com.bearsnake.khalehla.kdte.console.messages.PollInputMessageResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.hasInput_ = hasInput_;
      }
    }

    private void buildPartialOneofs(com.bearsnake.khalehla.kdte.console.messages.PollInputMessageResponse result) {
      result.inputSpecifierCase_ = inputSpecifierCase_;
      result.inputSpecifier_ = this.inputSpecifier_;
      if (inputSpecifierCase_ == 2 &&
          solicitedMessageBuilder_ != null) {
        result.inputSpecifier_ = solicitedMessageBuilder_.build();
      }
      if (inputSpecifierCase_ == 3 &&
          unsolicitedMessageBuilder_ != null) {
        result.inputSpecifier_ = unsolicitedMessageBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.bearsnake.khalehla.kdte.console.messages.PollInputMessageResponse) {
        return mergeFrom((com.bearsnake.khalehla.kdte.console.messages.PollInputMessageResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.bearsnake.khalehla.kdte.console.messages.PollInputMessageResponse other) {
      if (other == com.bearsnake.khalehla.kdte.console.messages.PollInputMessageResponse.getDefaultInstance()) return this;
      if (other.getHasInput() != false) {
        setHasInput(other.getHasInput());
      }
      switch (other.getInputSpecifierCase()) {
        case SOLICITEDMESSAGE: {
          mergeSolicitedMessage(other.getSolicitedMessage());
          break;
        }
        case UNSOLICITEDMESSAGE: {
          mergeUnsolicitedMessage(other.getUnsolicitedMessage());
          break;
        }
        case INPUTSPECIFIER_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              hasInput_ = input.readBool();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              input.readMessage(
                  getSolicitedMessageFieldBuilder().getBuilder(),
                  extensionRegistry);
              inputSpecifierCase_ = 2;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  getUnsolicitedMessageFieldBuilder().getBuilder(),
                  extensionRegistry);
              inputSpecifierCase_ = 3;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int inputSpecifierCase_ = 0;
    private java.lang.Object inputSpecifier_;
    public InputSpecifierCase
        getInputSpecifierCase() {
      return InputSpecifierCase.forNumber(
          inputSpecifierCase_);
    }

    public Builder clearInputSpecifier() {
      inputSpecifierCase_ = 0;
      inputSpecifier_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private boolean hasInput_ ;
    /**
     * <code>bool hasInput = 1;</code>
     * @return The hasInput.
     */
    @java.lang.Override
    public boolean getHasInput() {
      return hasInput_;
    }
    /**
     * <code>bool hasInput = 1;</code>
     * @param value The hasInput to set.
     * @return This builder for chaining.
     */
    public Builder setHasInput(boolean value) {

      hasInput_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>bool hasInput = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearHasInput() {
      bitField0_ = (bitField0_ & ~0x00000001);
      hasInput_ = false;
      onChanged();
      return this;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.bearsnake.khalehla.kdte.console.messages.SolicitedInputMessage, com.bearsnake.khalehla.kdte.console.messages.SolicitedInputMessage.Builder, com.bearsnake.khalehla.kdte.console.messages.SolicitedInputMessageOrBuilder> solicitedMessageBuilder_;
    /**
     * <code>.msg.SolicitedInputMessage solicitedMessage = 2;</code>
     * @return Whether the solicitedMessage field is set.
     */
    @java.lang.Override
    public boolean hasSolicitedMessage() {
      return inputSpecifierCase_ == 2;
    }
    /**
     * <code>.msg.SolicitedInputMessage solicitedMessage = 2;</code>
     * @return The solicitedMessage.
     */
    @java.lang.Override
    public com.bearsnake.khalehla.kdte.console.messages.SolicitedInputMessage getSolicitedMessage() {
      if (solicitedMessageBuilder_ == null) {
        if (inputSpecifierCase_ == 2) {
          return (com.bearsnake.khalehla.kdte.console.messages.SolicitedInputMessage) inputSpecifier_;
        }
        return com.bearsnake.khalehla.kdte.console.messages.SolicitedInputMessage.getDefaultInstance();
      } else {
        if (inputSpecifierCase_ == 2) {
          return solicitedMessageBuilder_.getMessage();
        }
        return com.bearsnake.khalehla.kdte.console.messages.SolicitedInputMessage.getDefaultInstance();
      }
    }
    /**
     * <code>.msg.SolicitedInputMessage solicitedMessage = 2;</code>
     */
    public Builder setSolicitedMessage(com.bearsnake.khalehla.kdte.console.messages.SolicitedInputMessage value) {
      if (solicitedMessageBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        inputSpecifier_ = value;
        onChanged();
      } else {
        solicitedMessageBuilder_.setMessage(value);
      }
      inputSpecifierCase_ = 2;
      return this;
    }
    /**
     * <code>.msg.SolicitedInputMessage solicitedMessage = 2;</code>
     */
    public Builder setSolicitedMessage(
        com.bearsnake.khalehla.kdte.console.messages.SolicitedInputMessage.Builder builderForValue) {
      if (solicitedMessageBuilder_ == null) {
        inputSpecifier_ = builderForValue.build();
        onChanged();
      } else {
        solicitedMessageBuilder_.setMessage(builderForValue.build());
      }
      inputSpecifierCase_ = 2;
      return this;
    }
    /**
     * <code>.msg.SolicitedInputMessage solicitedMessage = 2;</code>
     */
    public Builder mergeSolicitedMessage(com.bearsnake.khalehla.kdte.console.messages.SolicitedInputMessage value) {
      if (solicitedMessageBuilder_ == null) {
        if (inputSpecifierCase_ == 2 &&
            inputSpecifier_ != com.bearsnake.khalehla.kdte.console.messages.SolicitedInputMessage.getDefaultInstance()) {
          inputSpecifier_ = com.bearsnake.khalehla.kdte.console.messages.SolicitedInputMessage.newBuilder((com.bearsnake.khalehla.kdte.console.messages.SolicitedInputMessage) inputSpecifier_)
              .mergeFrom(value).buildPartial();
        } else {
          inputSpecifier_ = value;
        }
        onChanged();
      } else {
        if (inputSpecifierCase_ == 2) {
          solicitedMessageBuilder_.mergeFrom(value);
        } else {
          solicitedMessageBuilder_.setMessage(value);
        }
      }
      inputSpecifierCase_ = 2;
      return this;
    }
    /**
     * <code>.msg.SolicitedInputMessage solicitedMessage = 2;</code>
     */
    public Builder clearSolicitedMessage() {
      if (solicitedMessageBuilder_ == null) {
        if (inputSpecifierCase_ == 2) {
          inputSpecifierCase_ = 0;
          inputSpecifier_ = null;
          onChanged();
        }
      } else {
        if (inputSpecifierCase_ == 2) {
          inputSpecifierCase_ = 0;
          inputSpecifier_ = null;
        }
        solicitedMessageBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.msg.SolicitedInputMessage solicitedMessage = 2;</code>
     */
    public com.bearsnake.khalehla.kdte.console.messages.SolicitedInputMessage.Builder getSolicitedMessageBuilder() {
      return getSolicitedMessageFieldBuilder().getBuilder();
    }
    /**
     * <code>.msg.SolicitedInputMessage solicitedMessage = 2;</code>
     */
    @java.lang.Override
    public com.bearsnake.khalehla.kdte.console.messages.SolicitedInputMessageOrBuilder getSolicitedMessageOrBuilder() {
      if ((inputSpecifierCase_ == 2) && (solicitedMessageBuilder_ != null)) {
        return solicitedMessageBuilder_.getMessageOrBuilder();
      } else {
        if (inputSpecifierCase_ == 2) {
          return (com.bearsnake.khalehla.kdte.console.messages.SolicitedInputMessage) inputSpecifier_;
        }
        return com.bearsnake.khalehla.kdte.console.messages.SolicitedInputMessage.getDefaultInstance();
      }
    }
    /**
     * <code>.msg.SolicitedInputMessage solicitedMessage = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.bearsnake.khalehla.kdte.console.messages.SolicitedInputMessage, com.bearsnake.khalehla.kdte.console.messages.SolicitedInputMessage.Builder, com.bearsnake.khalehla.kdte.console.messages.SolicitedInputMessageOrBuilder> 
        getSolicitedMessageFieldBuilder() {
      if (solicitedMessageBuilder_ == null) {
        if (!(inputSpecifierCase_ == 2)) {
          inputSpecifier_ = com.bearsnake.khalehla.kdte.console.messages.SolicitedInputMessage.getDefaultInstance();
        }
        solicitedMessageBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.bearsnake.khalehla.kdte.console.messages.SolicitedInputMessage, com.bearsnake.khalehla.kdte.console.messages.SolicitedInputMessage.Builder, com.bearsnake.khalehla.kdte.console.messages.SolicitedInputMessageOrBuilder>(
                (com.bearsnake.khalehla.kdte.console.messages.SolicitedInputMessage) inputSpecifier_,
                getParentForChildren(),
                isClean());
        inputSpecifier_ = null;
      }
      inputSpecifierCase_ = 2;
      onChanged();
      return solicitedMessageBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.bearsnake.khalehla.kdte.console.messages.UnsolicitedInputMessage, com.bearsnake.khalehla.kdte.console.messages.UnsolicitedInputMessage.Builder, com.bearsnake.khalehla.kdte.console.messages.UnsolicitedInputMessageOrBuilder> unsolicitedMessageBuilder_;
    /**
     * <code>.msg.UnsolicitedInputMessage unsolicitedMessage = 3;</code>
     * @return Whether the unsolicitedMessage field is set.
     */
    @java.lang.Override
    public boolean hasUnsolicitedMessage() {
      return inputSpecifierCase_ == 3;
    }
    /**
     * <code>.msg.UnsolicitedInputMessage unsolicitedMessage = 3;</code>
     * @return The unsolicitedMessage.
     */
    @java.lang.Override
    public com.bearsnake.khalehla.kdte.console.messages.UnsolicitedInputMessage getUnsolicitedMessage() {
      if (unsolicitedMessageBuilder_ == null) {
        if (inputSpecifierCase_ == 3) {
          return (com.bearsnake.khalehla.kdte.console.messages.UnsolicitedInputMessage) inputSpecifier_;
        }
        return com.bearsnake.khalehla.kdte.console.messages.UnsolicitedInputMessage.getDefaultInstance();
      } else {
        if (inputSpecifierCase_ == 3) {
          return unsolicitedMessageBuilder_.getMessage();
        }
        return com.bearsnake.khalehla.kdte.console.messages.UnsolicitedInputMessage.getDefaultInstance();
      }
    }
    /**
     * <code>.msg.UnsolicitedInputMessage unsolicitedMessage = 3;</code>
     */
    public Builder setUnsolicitedMessage(com.bearsnake.khalehla.kdte.console.messages.UnsolicitedInputMessage value) {
      if (unsolicitedMessageBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        inputSpecifier_ = value;
        onChanged();
      } else {
        unsolicitedMessageBuilder_.setMessage(value);
      }
      inputSpecifierCase_ = 3;
      return this;
    }
    /**
     * <code>.msg.UnsolicitedInputMessage unsolicitedMessage = 3;</code>
     */
    public Builder setUnsolicitedMessage(
        com.bearsnake.khalehla.kdte.console.messages.UnsolicitedInputMessage.Builder builderForValue) {
      if (unsolicitedMessageBuilder_ == null) {
        inputSpecifier_ = builderForValue.build();
        onChanged();
      } else {
        unsolicitedMessageBuilder_.setMessage(builderForValue.build());
      }
      inputSpecifierCase_ = 3;
      return this;
    }
    /**
     * <code>.msg.UnsolicitedInputMessage unsolicitedMessage = 3;</code>
     */
    public Builder mergeUnsolicitedMessage(com.bearsnake.khalehla.kdte.console.messages.UnsolicitedInputMessage value) {
      if (unsolicitedMessageBuilder_ == null) {
        if (inputSpecifierCase_ == 3 &&
            inputSpecifier_ != com.bearsnake.khalehla.kdte.console.messages.UnsolicitedInputMessage.getDefaultInstance()) {
          inputSpecifier_ = com.bearsnake.khalehla.kdte.console.messages.UnsolicitedInputMessage.newBuilder((com.bearsnake.khalehla.kdte.console.messages.UnsolicitedInputMessage) inputSpecifier_)
              .mergeFrom(value).buildPartial();
        } else {
          inputSpecifier_ = value;
        }
        onChanged();
      } else {
        if (inputSpecifierCase_ == 3) {
          unsolicitedMessageBuilder_.mergeFrom(value);
        } else {
          unsolicitedMessageBuilder_.setMessage(value);
        }
      }
      inputSpecifierCase_ = 3;
      return this;
    }
    /**
     * <code>.msg.UnsolicitedInputMessage unsolicitedMessage = 3;</code>
     */
    public Builder clearUnsolicitedMessage() {
      if (unsolicitedMessageBuilder_ == null) {
        if (inputSpecifierCase_ == 3) {
          inputSpecifierCase_ = 0;
          inputSpecifier_ = null;
          onChanged();
        }
      } else {
        if (inputSpecifierCase_ == 3) {
          inputSpecifierCase_ = 0;
          inputSpecifier_ = null;
        }
        unsolicitedMessageBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.msg.UnsolicitedInputMessage unsolicitedMessage = 3;</code>
     */
    public com.bearsnake.khalehla.kdte.console.messages.UnsolicitedInputMessage.Builder getUnsolicitedMessageBuilder() {
      return getUnsolicitedMessageFieldBuilder().getBuilder();
    }
    /**
     * <code>.msg.UnsolicitedInputMessage unsolicitedMessage = 3;</code>
     */
    @java.lang.Override
    public com.bearsnake.khalehla.kdte.console.messages.UnsolicitedInputMessageOrBuilder getUnsolicitedMessageOrBuilder() {
      if ((inputSpecifierCase_ == 3) && (unsolicitedMessageBuilder_ != null)) {
        return unsolicitedMessageBuilder_.getMessageOrBuilder();
      } else {
        if (inputSpecifierCase_ == 3) {
          return (com.bearsnake.khalehla.kdte.console.messages.UnsolicitedInputMessage) inputSpecifier_;
        }
        return com.bearsnake.khalehla.kdte.console.messages.UnsolicitedInputMessage.getDefaultInstance();
      }
    }
    /**
     * <code>.msg.UnsolicitedInputMessage unsolicitedMessage = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.bearsnake.khalehla.kdte.console.messages.UnsolicitedInputMessage, com.bearsnake.khalehla.kdte.console.messages.UnsolicitedInputMessage.Builder, com.bearsnake.khalehla.kdte.console.messages.UnsolicitedInputMessageOrBuilder> 
        getUnsolicitedMessageFieldBuilder() {
      if (unsolicitedMessageBuilder_ == null) {
        if (!(inputSpecifierCase_ == 3)) {
          inputSpecifier_ = com.bearsnake.khalehla.kdte.console.messages.UnsolicitedInputMessage.getDefaultInstance();
        }
        unsolicitedMessageBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.bearsnake.khalehla.kdte.console.messages.UnsolicitedInputMessage, com.bearsnake.khalehla.kdte.console.messages.UnsolicitedInputMessage.Builder, com.bearsnake.khalehla.kdte.console.messages.UnsolicitedInputMessageOrBuilder>(
                (com.bearsnake.khalehla.kdte.console.messages.UnsolicitedInputMessage) inputSpecifier_,
                getParentForChildren(),
                isClean());
        inputSpecifier_ = null;
      }
      inputSpecifierCase_ = 3;
      onChanged();
      return unsolicitedMessageBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:msg.PollInputMessageResponse)
  }

  // @@protoc_insertion_point(class_scope:msg.PollInputMessageResponse)
  private static final com.bearsnake.khalehla.kdte.console.messages.PollInputMessageResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.bearsnake.khalehla.kdte.console.messages.PollInputMessageResponse();
  }

  public static com.bearsnake.khalehla.kdte.console.messages.PollInputMessageResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PollInputMessageResponse>
      PARSER = new com.google.protobuf.AbstractParser<PollInputMessageResponse>() {
    @java.lang.Override
    public PollInputMessageResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<PollInputMessageResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PollInputMessageResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.bearsnake.khalehla.kdte.console.messages.PollInputMessageResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

