// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: exec/msg/console.proto

package com.bearsnake.khalehla.kdte.console.messages;

public interface SolicitedInputMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:msg.SolicitedInputMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 messageId = 1;</code>
   * @return The messageId.
   */
  int getMessageId();

  /**
   * <code>string text = 2;</code>
   * @return The text.
   */
  java.lang.String getText();
  /**
   * <code>string text = 2;</code>
   * @return The bytes for text.
   */
  com.google.protobuf.ByteString
      getTextBytes();
}
